# coding: utf-8

"""
    Dynamicdns.pro

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dynamicdnsapi.api.subdomain_api import SubdomainApi


class TestSubdomainApi(unittest.TestCase):
    """SubdomainApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubdomainApi()

    def tearDown(self) -> None:
        pass

    def test_updateip(self) -> None:
        """Test case for updateip

        update the ip address with the connecting ip address
        """
        pass


if __name__ == '__main__':
    unittest.main()
