# coding: utf-8

"""
    Dynamicdns.pro

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dynamicdnsapi.models.updateip400_response import Updateip400Response

class TestUpdateip400Response(unittest.TestCase):
    """Updateip400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Updateip400Response:
        """Test Updateip400Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Updateip400Response`
        """
        model = Updateip400Response()
        if include_optional:
            return Updateip400Response(
                message = 'Invalid ip address'
            )
        else:
            return Updateip400Response(
                message = 'Invalid ip address',
        )
        """

    def testUpdateip400Response(self):
        """Test Updateip400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
