# coding: utf-8

"""
    Dynamicdns.pro

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dynamicdnsapi.models.update200_response_any_of import Update200ResponseAnyOf

class TestUpdate200ResponseAnyOf(unittest.TestCase):
    """Update200ResponseAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Update200ResponseAnyOf:
        """Test Update200ResponseAnyOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Update200ResponseAnyOf`
        """
        model = Update200ResponseAnyOf()
        if include_optional:
            return Update200ResponseAnyOf(
                message = 'Record updated'
            )
        else:
            return Update200ResponseAnyOf(
                message = 'Record updated',
        )
        """

    def testUpdate200ResponseAnyOf(self):
        """Test Update200ResponseAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
