# coding: utf-8

"""
    Dynamicdns.pro

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dynamicdnsapi.models.update403_response import Update403Response

class TestUpdate403Response(unittest.TestCase):
    """Update403Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Update403Response:
        """Test Update403Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Update403Response`
        """
        model = Update403Response()
        if include_optional:
            return Update403Response(
                message = 'You are not allowed to update this record'
            )
        else:
            return Update403Response(
                message = 'You are not allowed to update this record',
        )
        """

    def testUpdate403Response(self):
        """Test Update403Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
