# coding: utf-8

"""
    Dynamicdns.pro

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dynamicdnsapi.models.update400_response import Update400Response

class TestUpdate400Response(unittest.TestCase):
    """Update400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Update400Response:
        """Test Update400Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Update400Response`
        """
        model = Update400Response()
        if include_optional:
            return Update400Response(
                message = 'No ip address provided'
            )
        else:
            return Update400Response(
                message = 'No ip address provided',
        )
        """

    def testUpdate400Response(self):
        """Test Update400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
